version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pronas_postgres
    environment:
      POSTGRES_DB: pronas_pcd
      POSTGRES_USER: pronas_user
      POSTGRES_PASSWORD: pronas_2025_secure
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pronas_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pronas_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    container_name: pronas_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - pronas_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: pronas_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pronas_network
    restart: unless-stopped
    command: redis-server --appendonly yes

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pronas_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://pronas_user:pronas_2025_secure@postgres:5432/pronas_pcd
      - QDRANT_URL=http://qdrant:6333
      - REDIS_URL=redis://redis:6379
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SECRET_KEY=change-this-secret-key-in-production-min-32-chars
    volumes:
      - ./backend:/app
      - ./data:/data
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - pronas_network
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pronas_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - pronas_network
    restart: unless-stopped

networks:
  pronas_network:
    driver: bridge

volumes:
  postgres_data:
  qdrant_data:
  redis_data:
